`define pretrained      1
`define numLayers       1
`define dataWidth       16
`define numData         5
`define numNeuronLayer1 1
`define numWeightLayer1 5
`define Layer1ActType   "regression"
`define weightIntWidth  1
`define weightValWidth  `dataWidth
`define biasValWidth    `dataWidth
`define MaxTestSamples  2